FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80 
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app_publish

FROM base AS final
WORKDIR /app
COPY --from=build /app_publish .
ENTRYPOINT ["dotnet", "SimpleBank.Customers.Api.dll"]